# Database Initialization

create database if not exists smart_bi_db;
use smart_bi_db;

-- User table
create table if not exists user (
    id            bigint auto_increment comment 'id'     primary key,
    user_account  varchar(256)                           not null comment 'Account',
    user_password varchar(512)                           not null comment 'Password',
    user_name     varchar(256)                           null comment 'Nickname',
    user_avatar   varchar(1024)                          null comment 'Avatar',
    user_role     varchar(256) default 'user'            not null comment 'Role：user/admin',
    create_time   datetime     default CURRENT_TIMESTAMP not null comment 'Created Time',
    update_time   datetime     default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment 'Updated time',
    is_deleted    tinyint      default 0                 not null comment 'Is deleted?',
    index idx_user_account (user_account)
) comment 'User' collate = utf8mb4_unicode_ci;

-- Chart Info table
create table if not exists chart (
     id             bigint auto_increment comment 'id'     primary key,
     goal           text                                   null comment 'Analysis goal',
     `name`         varchar(128)                           null comment 'Chart name',
     chart_data     text                                   null comment 'Data of chart',
     chart_type     varchar(128)                           null comment 'Chart type',
     gen_chart      text                                   null comment 'Chart generated by AI',
     gen_result     text                                   null comment 'Result generated by AI',
     `status`       varchar(128) default 'wait'            not null comment 'wait, running, succeed, failed',
     exec_message   text                                   null comment 'execution message',
     user_id        bigint                                 null comment 'user id that creates it',
     create_time    datetime     default CURRENT_TIMESTAMP not null comment 'Created Time',
     update_time    datetime     default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment 'Updated time',
     is_deleted     tinyint      default 0                 not null comment 'Is deleted?'
) comment 'User' collate = utf8mb4_unicode_ci;