package com.gavinjin.smartbibackend.model.domain;

import com.baomidou.mybatisplus.annotation.*;

import java.io.Serializable;
import java.util.Date;

/**
 * Chart
 * @TableName chart
 */
@TableName(value ="chart")
public class Chart implements Serializable {
    /**
     * id
     */
    @TableId(type = IdType.ASSIGN_ID)
    private Long id;

    /**
     * Analysis goal
     */
    private String goal;

    /**
     * Data of chart
     */
    private String chartData;

    /**
     * Chart type
     */
    private String chartType;

    /**
     * Chart generated by AI
     */
    private String genChart;

    /**
     * Result generated by AI
     */
    private String genResult;

    /**
     * Created Time
     */
    private Date createTime;

    /**
     * Updated time
     */
    private Date updateTime;

    /**
     * Is deleted?
     */
    @TableLogic
    private Integer isDeleted;

    @TableField(exist = false)
    private static final long serialVersionUID = 1L;

    /**
     * id
     */
    public Long getId() {
        return id;
    }

    /**
     * id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Analysis goal
     */
    public String getGoal() {
        return goal;
    }

    /**
     * Analysis goal
     */
    public void setGoal(String goal) {
        this.goal = goal;
    }

    /**
     * Data of chart
     */
    public String getChartData() {
        return chartData;
    }

    /**
     * Data of chart
     */
    public void setChartData(String chartData) {
        this.chartData = chartData;
    }

    /**
     * Chart type
     */
    public String getChartType() {
        return chartType;
    }

    /**
     * Chart type
     */
    public void setChartType(String chartType) {
        this.chartType = chartType;
    }

    /**
     * Chart generated by AI
     */
    public String getGenChart() {
        return genChart;
    }

    /**
     * Chart generated by AI
     */
    public void setGenChart(String genChart) {
        this.genChart = genChart;
    }

    /**
     * Result generated by AI
     */
    public String getGenResult() {
        return genResult;
    }

    /**
     * Result generated by AI
     */
    public void setGenResult(String genResult) {
        this.genResult = genResult;
    }

    /**
     * Created Time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * Created Time
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * Updated time
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * Updated time
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Is deleted?
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * Is deleted?
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}