package com.gavinjin.smartbibackend.model.domain;

import com.baomidou.mybatisplus.annotation.*;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Chart
 * @TableName chart
 */
@TableName(value ="chart")
@Data
public class Chart implements Serializable {
    /**
     * id
     */
    @TableId(type = IdType.ASSIGN_ID)
    private Long id;

    /**
     * Analysis goal
     */
    private String goal;

    /**
     * Data of chart
     */
    private String chartData;

    /**
     * Chart type
     */
    private String chartType;

    /**
     * Chart generated by AI
     */
    private String genChart;

    /**
     * Result generated by AI
     */
    private String genResult;

    /**
     * User id
     */
    private Long userId;

    /**
     * Created Time
     */
    private Date createTime;

    /**
     * Updated time
     */
    private Date updateTime;

    /**
     * Is deleted?
     */
    @TableLogic
    private Integer isDeleted;

    @TableField(exist = false)
    private static final long serialVersionUID = 1L;
}